fix: system tests
Backbase/twilio-sms-connector pull request #6
Opened 2022-11-24 12:31 UTC by kamyarbb

2022-11-24 15:45 UTC, ex0b1t requested changes

2022-11-24 15:45 UTC, ex0b1t commented on src/test/resources/application-system-test.yaml
> +      function.definition: commLowPriority;commMediumPriority;commHighPriority;trackingFunction
Why is this here and not in the default application.yml. This means that if I run the jar file or docker image it is not currently configured to listen to SMS?

2022-11-24 15:45 UTC, ex0b1t commented on src/test/resources/application-system-test.yaml
> +      function.definition: commLowPriority;commMediumPriority;commHighPriority;trackingFunction
This default config has to be moved to the application.yml

2022-11-28 12:56 UTC, afsinka-backbase commented on pom.xml
> -            <version>${testcontainers.version}</version>
you updated version number in line31 but removed here?

2022-11-28 12:57 UTC, ex0b1t commented on pom.xml
> -            <version>${testcontainers.version}</version>
Yea you also have the BOM managing the version so can remove this

2022-11-28 12:58 UTC, ex0b1t submitted a review, later dismissed

2022-11-28 13:02 UTC, afsinka-backbase commented on src/test/resources/application.yaml
> +      function.definition: trackingFunction
in `src/test/resources/application-system-test.yaml` line42 you also have `trackingFunction`
if you copy ` trackingFunction-in-0:` property from this file to that file and replace `commTracking-out-0:` in there maybe you do not even need any spring property in this file but not sure, just saying so you make sure which config is active.

2022-11-28 13:06 UTC, afsinka-backbase commented on pom.xml
> +        <mapstruct.version>1.5.2.Final</mapstruct.version>
is this duplicate with line.17?

2022-11-28 13:09 UTC, afsinka-backbase commented on src/test/resources/application-system-test.yaml
> +      function.definition: commLowPriority;commMediumPriority;commHighPriority;trackingFunction
you have `trackingFunction` here but you have different name in line54

2022-11-28 13:12 UTC, afsinka-backbase commented on src/test/resources/application-system-test.yaml
> +        commTracking-out-0:
I confused
why do you need `trackingFunction` in `src/test/resources/application.yaml` 
and why you have this `commTracking` here even when you do not have in line.42?

2022-11-28 13:14 UTC, afsinka-backbase commented on src/test/resources/application-system-test.yaml
> +        sms-medium-priority:
is this duplicated with line49? and not mentioned in line42? do probably you do not need this

2022-11-28 13:15 UTC, afsinka-backbase commented on src/test/resources/application.yaml
> +      function.definition: trackingFunction
do you need this or active config is in `src/test/resources/application-system-test.yaml` ?

2022-11-28 15:05 UTC, kamyarbb commented on src/test/resources/application.yaml
> +         trackingFunction-in-0:
I'm using a tracking function to receive tracking message generated by the connector to verify the delivery.

2022-11-28 15:06 UTC, kamyarbb commented on src/test/resources/application.yaml
> +      function.definition: trackingFunction
I'm using a tracking function to receive tracking message generated by the connector to verify the delivery.

2022-11-28 15:29 UTC, afsinka-backbase commented on pom.xml
> -    </properties>
I do not know if my eyes are dead but is `</properties` missing now?

2022-11-28 15:35 UTC, afsinka-backbase commented on src/test/resources/application-system-test.yaml
> +        commTracking-out-0:
I think you still have `commTracking` here but do you need it?
in general what you have written in `function.definition` and `bindings` should be consistent because that's how spring integrates them. `myFunction` --> `myFunction-in-0` or `myFunction` --> `myFunction-out-0`

2022-11-28 15:37 UTC, afsinka-backbase commented on src/test/resources/application.yaml
> +      function.definition: trackingFunction
if you are clear about if it should be `in` or `out` and if it is overriden by the values in `src/test/resources/application-system-test.yaml` or not then okay

2022-11-28 15:43 UTC, kamyarbb commented on src/test/resources/application.yaml
> +      function.definition: trackingFunction
I check it. New properties file override values in `application.yaml`. So i have to copy them form `application.yaml` to new file. the bad thing is that, when you add new binding, all bindings should be defined again.

2022-11-28 15:48 UTC, afsinka-backbase approved these changes

2022-11-29 08:52 UTC, ex0b1t approved these changes

2022-11-29 08:57 UTC, merged